export const mockData = [
  {
    username: "@adventure_jane",
    caption: "Exploring the mountains today! 🌄 #AdventureAwaits #NatureLover",
    hashtags: ["#Hiking", "#Travel", "#Mountains"],
    likes: 1024,
    comments: [
      { user: "@travel_guru", comment: "Incredible view!" },
      { user: "@nature_fan", comment: "Looks so peaceful!" },
    ],
    image: "Panoramic shot of a mountain range.",
  },
  {
    username: "@foodie_mike",
    caption: "Best pasta in town! 🍝 #Foodie #ItalianCuisine",
    hashtags: ["#PastaLover", "#FoodGram", "#Delicious"],
    likes: 876,
    comments: [
      { user: "@gourmet_lover", comment: "That looks amazing!" },
      { user: "@chef_maria", comment: "Recipe, please? 😋" },
    ],
    image: "Close-up of a plate of pasta with marinara sauce.",
  },
  {
    username: "@urban_artist",
    caption: "New mural completed in the city! 🎨 #StreetArt #Creativity",
    hashtags: ["#ArtInTheCity", "#UrbanArt", "#Mural"],
    likes: 1342,
    comments: [
      { user: "@art_enthusiast", comment: "Love the colors!" },
      { user: "@street_style", comment: "Stunning work!" },
    ],
    image: "A vibrant mural on a brick wall.",
  },
  {
    username: "@travel_with_me",
    caption: "Wanderlust taking over ✈️ #TravelGoals #SeeTheWorld",
    hashtags: ["#JetSetter", "#Explore", "#Travel"],
    likes: 1934,
    comments: [
      { user: "@globe_trotter", comment: "Where are you off to next?" },
      { user: "@dreamer", comment: "Take me with you!" },
    ],
    image: "Aerial view of a plane flying over the ocean.",
  },
  {
    username: "@fitness_fanatic",
    caption:
      "Push yourself, because no one else is going to do it for you! 💪 #FitnessMotivation",
    hashtags: ["#Workout", "#GymLife", "#NoPainNoGain"],
    likes: 1200,
    comments: [
      { user: "@fit_inspiration", comment: "So true!" },
      { user: "@health_journey", comment: "Keep pushing!" },
    ],
    image: "A person lifting weights in a gym.",
  },
  {
    username: "@sunset_chaser",
    caption: "Chasing the sun 🌅 #GoldenHour",
    hashtags: ["#Sunset", "#Nature", "#Photography"],
    likes: 2450,
    comments: [
      { user: "@photo_addict", comment: "Breathtaking!" },
      { user: "@sky_love", comment: "I live for moments like this!" },
    ],
    image: "A beautiful sunset over the ocean.",
  },
  {
    username: "@tech_savvy",
    caption: "Unboxing the latest gadget! 📱 #TechLife",
    hashtags: ["#Unboxing", "#Gadgets", "#TechReview"],
    likes: 890,
    comments: [
      { user: "@gadget_guru", comment: "Can't wait to see your review!" },
      { user: "@tech_addict", comment: "Looks sleek!" },
    ],
    image: "A person unboxing a new smartphone.",
  },
  {
    username: "@pet_paradise",
    caption: "My little furball 🐾 #PetLove",
    hashtags: ["#DogLover", "#CutePets", "#FurryFriends"],
    likes: 3100,
    comments: [
      { user: "@pet_lover", comment: "So adorable!" },
      { user: "@animal_fanatic", comment: "What a cutie!" },
    ],
    image: "A fluffy puppy playing in the grass.",
  },
  {
    username: "@coffee_addict",
    caption: "Morning brew ☕ #CoffeeTime",
    hashtags: ["#CaffeineFix", "#CoffeeLover", "#MorningRoutine"],
    likes: 950,
    comments: [
      { user: "@morning_glow", comment: "Nothing better than a fresh cup!" },
      { user: "@java_junkie", comment: "I need one right now!" },
    ],
    image: "A steaming cup of coffee on a wooden table.",
  },
  {
    username: "@fashion_fever",
    caption: "Today's look: Casual chic 👗 #OOTD",
    hashtags: ["#Fashion", "#StyleInspo", "#CasualOutfit"],
    likes: 1450,
    comments: [
      { user: "@style_maven", comment: "Love your outfit!" },
      { user: "@trendsetter", comment: "Where did you get that top?" },
    ],
    image: "A person posing in a stylish outfit.",
  },
  {
    username: "@food_fusion",
    caption: "Bringing flavors together 🍣🍕 #FusionCuisine",
    hashtags: ["#FoodInnovation", "#TasteExplosion", "#Yummy"],
    likes: 720,
    comments: [
      { user: "@chef_master", comment: "That looks so unique!" },
      { user: "@food_craver", comment: "Can't wait to try this!" },
    ],
    image: "A fusion dish combining sushi and pizza elements.",
  },
  {
    username: "@car_enthusiast",
    caption: "Dream ride 🚗 #CarGoals",
    hashtags: ["#Supercar", "#AutoAddict", "#LuxuryLife"],
    likes: 2100,
    comments: [
      { user: "@speed_demon", comment: "That's a beauty!" },
      { user: "@lux_life", comment: "Ultimate dream car!" },
    ],
    image: "A sleek sports car parked in front of a modern house.",
  },
  {
    username: "@bookworm_life",
    caption: "Getting lost in a good book 📚 #BookLover",
    hashtags: ["#ReadingTime", "#Bookstagram", "#Literature"],
    likes: 860,
    comments: [
      { user: "@lit_geek", comment: "What's the title?" },
      { user: "@story_addict", comment: "Looks like a great read!" },
    ],
    image: "A person reading a book by the window on a rainy day.",
  },
  {
    username: "@fitness_motivation",
    caption: "No excuses, just results 🏋️‍♂️ #GrindTime",
    hashtags: ["#WorkoutRoutine", "#FitnessGoals", "#HealthJourney"],
    likes: 1350,
    comments: [
      { user: "@gym_rat", comment: "Killing it!" },
      { user: "@fitfam", comment: "Inspiring as always!" },
    ],
    image: "A person doing pull-ups at an outdoor gym.",
  },
  {
    username: "@travel_junkie",
    caption: "Next stop: Paradise 🏝️ #BeachVibes",
    hashtags: ["#TravelAddict", "#TropicalEscape", "#Wanderlust"],
    likes: 1900,
    comments: [
      { user: "@beach_bum", comment: "Take me there!" },
      { user: "@sun_chaser", comment: "Looks like heaven!" },
    ],
    image: "A pristine beach with crystal-clear water and palm trees.",
  },
  {
    username: "@urban_explorer",
    caption: "Finding beauty in the city 🌆 #CityScapes",
    hashtags: ["#UrbanPhotography", "#CityLife", "#Architecture"],
    likes: 1120,
    comments: [
      { user: "@city_wanderer", comment: "Great shot!" },
      { user: "@street_scene", comment: "Love the composition!" },
    ],
    image: "A bustling city street at dusk with tall buildings.",
  },
  {
    username: "@artsy_soul",
    caption: "Expressing myself through colors 🎨 #ArtIsLife",
    hashtags: ["#CreativeMind", "#Painting", "#Art"],
    likes: 780,
    comments: [
      { user: "@color_craze", comment: "Beautiful work!" },
      { user: "@art_love", comment: "So much emotion in this piece!" },
    ],
    image: "A colorful abstract painting on a canvas.",
  },
  {
    username: "@culinary_delights",
    caption: "A little taste of heaven 🍰 #DessertLover",
    hashtags: ["#Baking", "#SweetTooth", "#Yum"],
    likes: 1045,
    comments: [
      { user: "@sugar_rush", comment: "That looks divine!" },
      { user: "@dessert_dreams", comment: "Is that homemade?" },
    ],
    image: "A slice of decadent chocolate cake on a white plate.",
  },
  {
    username: "@music_journey",
    caption: "Feeling the rhythm 🎶 #MusicIsLife",
    hashtags: ["#Guitar", "#LiveMusic", "#Melody"],
    likes: 1280,
    comments: [
      { user: "@sound_vibes", comment: "Such a vibe!" },
      { user: "@music_maniac", comment: "What song are you playing?" },
    ],
    image: "A person playing an acoustic guitar at a live event.",
  },
  {
    username: "@wildlife_lover",
    caption: "In the wild 🦁 #SafariAdventure",
    hashtags: ["#WildlifePhotography", "#Nature", "#Animals"],
    likes: 2020,
    comments: [
      { user: "@nature_watcher", comment: "Amazing capture!" },
      { user: "@animal_kingdom", comment: "Majestic creature!" },
    ],
    image: "A lion roaming the savannah during sunset.",
  },
];
